name: 'SCM_Customer_Modeling'
version: '1.0'
config-version: 2
profile: 'my_snowflake_profile'
require-dbt-version: ['>=1.0.0', '<2.0.0']

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  SCM_DBT_CUST:
    +materialized: view
    +schema: SCM_DBT_CUST
dbt-cloud:
    project-id: 70471823534967ame: 'my_snowflake_profile'
version: '1.0'
config-version: 2
profile: 'my_snowflake_profile'
require-dbt-version: ['>=1.0.0', '<2.0.0']

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  SCM_DBT_CUST:
    +materialized: view
    +schema: SCM_DBT_CUST
dbt-cloud:
    project-id: 70471823534967